### ISSUE TITLE
Glossaryの翻訳

### ISSUE THREAD

**Issue by mitsuruog** [angular/angular-ja#1]
- refs: [Workflow of Angular\.io Localisation \- Google Docs](https://docs.google.com/document/d/1p_H-8C-d74n9UHl0-5y2Xg6gdkagRQfCgI6Dh9ukkF8/edit?ts=57a3c671#heading=h.5yrttcw0l7ky)

> Start with glossary.jade and discuss the terms within the team, so that all team members use the same terms throughout.

公式で推奨しているようまず、日本語の用語集を決めた方がスムーズかと思います。

**Comment by mitsuruog** [comment]
というか、こいつを最初に翻訳しましょうねという話だったみたい。

- https://github.com/angular/angular-ja/blob/master/public/docs/ts/latest/glossary.jade

**Comment by laco0416** [comment]
frenchも最初はglossaryからですね 
https://github.com/angular/angular-fr/pull/42
参考になりそう。
