### ISSUE TITLE
{tools/cli/deployment} の翻訳

### ISSUE THREAD

**Issue by darkss-xyzzy** [angular/angular-ja#1003]
## 翻訳宣言
遅くなりましたが、ようやく動けそうですので、
tools/cli/deploymentを翻訳します。

### 翻訳するファイル

https://angular.jp/tools/cli/deployment

### 備考
前バージョンの翻訳がある程度使いまわせる見込みですが、
長いですので、お時間いただくと思います。

cc/ @lacolaco

**Comment by lacolaco** [comment]
@darkss-xyzzy ありがとうございます！よろしくお願いいたします

**Comment by darkss-xyzzy** [comment]
@lacolaco 
分量が前バージョンより少なくなっていたこともあり、思ったより早く完了しました。
プルリクエストを送りましたので、レビューをお願いします。
