### ISSUE TITLE
guide/npm-packages.mdの翻訳

### ISSUE THREAD

**Issue by sayanaka** [angular/angular-ja#108]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

guide/npm-packages.md

### 備考

このようなことをするのは人生で初めてなのですが、頑張りたいと思います。
レビュー等、よろしくお願いいたします！

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇

だれでも最初ははじめてなので気軽にどうぞ！
