### ISSUE TITLE
guide/service-worker-devops.mdの[追加]翻訳

### ISSUE THREAD

**Issue by studioTeaTwo** [angular/angular-ja#118]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

service-worker-devops.md

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
