### ISSUE TITLE
guide/structural-directives.mdの翻訳

### ISSUE THREAD

**Issue by studioTeaTwo** [angular/angular-ja#129]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

guide/structural-directives.md

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇

**Comment by studioTeaTwo** [comment]
一旦、リリースします🙇‍♀️
