### ISSUE TITLE
guide/displaying-data.mdの翻訳

### ISSUE THREAD

**Issue by mitsuhisaT** [angular/angular-ja#133]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x ] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

* guide/displaying-data.md

終わり次第、次の章に進もうと思います。

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇

**Comment by mitsuhisaT** [comment]
#78 と被っていたので、一旦取り下げます。Closeにします。
