### ISSUE TITLE
guide/dynamic-component-loaderの翻訳

### ISSUE THREAD

**Issue by mitsuhisaT** [angular/angular-ja#134]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x ] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

* guide/dynamic-component-loader

### 備考

最初なので、少な目の章にしました。
次からは、お行儀よく進める予定です。

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇

**Comment by lacolaco** [comment]
Closed by #135
