### ISSUE TITLE
guide/displaying-dataの翻訳

### ISSUE THREAD

**Issue by mitsuhisaT** [angular/angular-ja#136]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

* guide/displaying-data.md
解放して頂いたので、担当させて頂きます。

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇

**Comment by lacolaco** [comment]
終了しましたのでcloseします
