### ISSUE TITLE
guide/template-syntax.mdの翻訳

### ISSUE THREAD

**Issue by TomohiroAkutsu** [angular/angular-ja#140]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル
guide/template-syntax.md

### 備考
量が多いので少し時間かかるかもですが、しばしお待ちを 🙇

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇

**Comment by lacolaco** [comment]
長い間アクションがないためcloseさせていただきます。再開する際はあらためてチェックアウトをお願いします。
