### ISSUE TITLE
guide/lifecycle-hooks.md の翻訳

### ISSUE THREAD

**Issue by mitsuhisaT** [angular/angular-ja#143]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [ x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

* guide/lifecycle-hooks.md

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
