### ISSUE TITLE
guide/observables の翻訳

### ISSUE THREAD

**Issue by Pittan** [angular/angular-ja#148]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

- guide/observables.md

### 備考

RxJSの勉強をしつつ同時に翻訳していくスタイルでいきます！

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
