### ISSUE TITLE
guide/component-interaction.md の翻訳

### ISSUE THREAD

**Issue by mitsuhisaT** [angular/angular-ja#155]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

1. guid/component-interaction.md

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
