### ISSUE TITLE
guide/ngmodule-vs-jsmodule の翻訳

### ISSUE THREAD

**Issue by ukyo** [angular/angular-ja#162]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

* guide/ngmodule-vs-jsmodule.md

### 備考

NgModule以下を順番に片付けていこうかと思います

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
