### ISSUE TITLE
guide/frequent-ngmodules の翻訳

### ISSUE THREAD

**Issue by ukyo** [angular/angular-ja#164]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

* guide/frequent-ngmodules

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
