### ISSUE TITLE
guide/styleguideの翻訳

### ISSUE THREAD

**Issue by arayaryoma** [angular/angular-ja#178]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [ x ] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

[guide/styleguide.md](https://github.com/angular/angular-ja/blob/master/aio-ja/content/guide/styleguide.md)

### 備考

長いので1~2週間かかると思いますががんばります。

**Comment by lacolaco** [comment]
大変だと思いますがよろしくお願いします！全部じゃなくても切りの良いところまで途中まででも構いませんよ 🙆‍♂️
