### ISSUE TITLE
guide/module-types.md の翻訳

### ISSUE THREAD

**Issue by ukyo** [angular/angular-ja#183]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [ x ] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

* guide/module-types.md

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
