### ISSUE TITLE
guide/upgrade.md の翻訳

### ISSUE THREAD

**Issue by studioTeaTwo** [angular/angular-ja#185]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

guide/upgrade.md

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇

**Comment by studioTeaTwo** [comment]
時間取れそうにないので一旦リリースします。

**Comment by diodario** [comment]
@lacolaco 
こちらのファイル、引き継いで翻訳しようかと思うのですが、新しくissueを立てた方が良いでしょうか？

**Comment by lacolaco** [comment]
@diodario はい、新たに立ててもらいたいです！
