### ISSUE TITLE
guide/lazy-loading-ngmodules の翻訳

### ISSUE THREAD

**Issue by ukyo** [angular/angular-ja#205]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [ x ] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

* guide/lazy-loading-ngmodules

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
