### ISSUE TITLE
guide/elements.mdの翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#216]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

guide/elements.md

### 備考

後半に新しく追加されたセクションの追加翻訳を募集します。

https://github.com/angular/angular-ja/blob/master/aio-ja/content/guide/elements.md

**Comment by k-shirahama** [comment]
@lacolaco 翻訳やります！

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
