### ISSUE TITLE
guide/architecture-modulesの翻訳

### ISSUE THREAD

**Issue by silverskyvicto** [angular/angular-ja#221]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

guide/architecture-modules.md

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
