### ISSUE TITLE
guide/typescript-configurationの翻訳（再宣言）

### ISSUE THREAD

**Issue by sayanaka** [angular/angular-ja#224]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

guide/typescript-configuration.md

### 備考

#139 の再宣言です。
初稿はできたので、直後にプルリクエスト発行します。

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
