### ISSUE TITLE
guide/architecture-components.md の翻訳

### ISSUE THREAD

**Issue by silverskyvicto** [angular/angular-ja#227]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

guide/architecture-components.md

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
