### ISSUE TITLE
guide/architecture-services.md の翻訳

### ISSUE THREAD

**Issue by silverskyvicto** [angular/angular-ja#233]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル
guide/architecture-services.md

### 備考
なし

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
