### ISSUE TITLE
guide/dependency-injection.md の翻訳

### ISSUE THREAD

**Issue by silverskyvicto** [angular/angular-ja#249]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

guide/dependency-injection.md

### 備考

分量が多いようなので、複数回に分けてコミットする可能性あり

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
複数回のコミットも問題なしです。

**Comment by lacolaco** [comment]
こちらぜんぶ終わってましたね。ありがとうございました！
