### ISSUE TITLE
guide/styleguideの翻訳 （01-01 〜 02-04 まで）

### ISSUE THREAD

**Issue by tronperidot** [angular/angular-ja#255]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

[guide/styleguide.md](https://github.com/angular/angular-ja/blob/master/aio-ja/content/guide/styleguide.md)

### 備考

項番 02-04 まで行います。
量が多いので、小分けにしてissueを立てて行きます。

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
