### ISSUE TITLE
guide/universal.md の翻訳

### ISSUE THREAD

**Issue by MasanobuAkiba** [angular/angular-ja#259]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

- [guide/universal.md](https://github.com/angular/angular-ja/blob/master/aio-ja/content/guide/universal.md)

### 備考

新バージョンで書き直し中です...

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇

**Comment by silverskyvicto** [comment]
@lacolaco 
これ止まっているならやりましょうか？

**Comment by lacolaco** [comment]
@silverskyvicto しばらく動いていないので、もしやっていただけるなら助かります！

**Comment by silverskyvicto** [comment]
@lacolaco 
じゃやりますね
