### ISSUE TITLE
guide/complex-animation-sequences.md の翻訳

### ISSUE THREAD

**Issue by ver-1000000** [angular/angular-ja#261]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル
- guide/complex-animation-sequences.md

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
