### ISSUE TITLE
guide/dependency-injection-providers.mdの翻訳

### ISSUE THREAD

**Issue by kojiGit55** [angular/angular-ja#272]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

guide/dependency-injection-providers.md

**Comment by silverskyvicto** [comment]
@lacolaco 
これ手付かずならやりましょうか？

**Comment by kojiGit55** [comment]
長い間手付かずになってしまって本当に申し訳ないです。
よろしければ、引き取っていただけると幸いです。

**Comment by lacolaco** [comment]
引き継ぎありがとうございます。

現在 #425 が進行中なので、その完了後にお願いします！
