### ISSUE TITLE
CLIのサブコマンドの目次が表示されていない

### ISSUE THREAD

**Issue by ukyo** [angular/angular-ja#276]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [ ] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ x ] その他
```

サブコマンド一覧が表示されていないようです。

<img width="238" alt="2019-01-11 15 59 31" src="https://user-images.githubusercontent.com/373554/51018209-1f048100-15ba-11e9-8f63-f537ccd6dbb0.png">

<img width="267" alt="2019-01-11 15 59 42" src="https://user-images.githubusercontent.com/373554/51018218-24fa6200-15ba-11e9-9cac-12c1ea0e765a.png">

**Comment by lacolaco** [comment]
原因がわかりました。CLIのコマンドリストはaioのビルド時に `@angular/cli` のパッケージから動的に生成されてるんですが、SideNavに挿入する処理が名前に依存してました

https://github.com/angular/angular/blob/master/aio/tools/transforms/cli-docs-package/processors/processCliCommands.js#L7

```
const navigationNode = navigationDoc && navigationDoc.data['SideNav'].find(node => node.title === 'CLI Commands');
```

この処理を書き換えて日本語に対応するようにしてもよいのですが、けっこうデリケートな部分な気がするので、目次の方を英語に戻して解決します。
