### ISSUE TITLE
チートシートの文字の折り返しが効いていない箇所が存在する

### ISSUE THREAD

**Issue by silverskyvicto** [angular/angular-ja#284]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [ ] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [x] その他
```

あまり優先度は高くないですが、チートシートのページにある「ブートストラップ」のテーブルの中でメソッドの文字の折り返しが効いていないみたいです。
MacOS に Firefox でみた時に確認しました。

https://angular.jp/guide/cheatsheet

**Comment by lacolaco** [comment]
報告ありがとうございます！
特定のviewportのときだけみたいですね
英語版でも同じですので、ja側で特別に対応はしないでもよいかと思います。
