### ISSUE TITLE
guide/dependency-injection-navtree.md の翻訳

### ISSUE THREAD

**Issue by silverskyvicto** [angular/angular-ja#285]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

guide/dependency-injection-navtree.md

### 備考

場合によっては分割してコミットする可能性あり

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
