### ISSUE TITLE
guide/file-structureの翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#286]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

guide/file-structure.md

https://angular.jp/guide/file-structure

### 備考

内容は比較的短めです。

**Comment by renamoo** [comment]
初めまして、こちらの翻訳やってみたいです！

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
