### ISSUE TITLE
[PR募集] guide/workspace-config の翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#294]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

guide/workspace-config.md
https://angular.jp/guide/workspace-config

### 備考

短めなので、Angular CLIの基本的な知識があれば翻訳できると思います。

**Comment by himatani** [comment]
@lacolaco こちら翻訳します！（諸事情でアカウント変えました。 [@kappy](https://github.com/kappy) です。前のアカウントはそのうち消します）

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
