### ISSUE TITLE
[PR募集] guide/npm-packages の翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#295]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

guide/npm-packages
https://angular.jp/guide/npm-packages

### 備考

Angularに関連するnpmパッケージについてのリファレンス的なガイドです。短い文章のまとまりなので翻訳しやすいと思います

**Comment by nana4gonta** [comment]
興味あります🙋‍♂️

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
翻訳中にわからないことがあったら気兼ねなく質問してください！
