### ISSUE TITLE
[PR募集] guide/build の翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#296]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

guide/build.md
https://angular.jp/guide/build

### 備考

短いページですので初めてのコントリビューションにおすすめです

**Comment by tkiryu** [comment]
こちらの翻訳やろうと思います！

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
翻訳中にわからないことがあったら気兼ねなく質問してください！
