### ISSUE TITLE
guide/deployment の翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#297]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

guide/deployment.md
https://angular.jp/guide/deployment

### 備考

短いページなのではじめてのコントリビューションにおすすめです

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
翻訳中にわからないことがあったら気兼ねなく質問してください！

**Comment by yasmiyazaki** [comment]
@euxn23 
こちらもし対応が止まっているようであれば引き取らせていただきたいのですがご対応状況いかがでしょうか。

**Comment by lacolaco** [comment]
@euxn23 長い間アクションがないため、アサインを取り消させていただきます。

@yasmiyazaki こちら、やっていただけるのでしたらぜひよろしくおねがいします！

**Comment by yasmiyazaki** [comment]
ありがとうございます。翻訳対応始めさせていただきます。

**Comment by doutori** [comment]
こちらの件、止まっているようでしたら巻き取ってしまってよいでしょうか?

**Comment by lacolaco** [comment]
@yasmiyazaki 長い間アクションがないため、宣言を取り消させていただきます。
@doutori ぜひよろしくおねがいします！

**Comment by lacolaco** [comment]
長い間アクションがないためcloseさせていただきます。再開する際はあらためてチェックアウトをお願いします。
