### ISSUE TITLE
[PR募集] guide/browser-support の翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#298]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

guide/browser-support.md
https://angular.jp/guide/browser-support

### 備考

簡単なのではじめてのコントリビューションにおすすめです

**Comment by nagamoto** [comment]
@lacolaco 
こちらの翻訳やってもいいでしょうか？
https://github.com/angular/angular-ja/blob/master/README.md#%E7%BF%BB%E8%A8%B3%E4%BD%9C%E6%A5%AD
こちらをよく読んで取り組みますが、何か問題あれば言ってください

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
なにか翻訳中にわからないことがあったら気兼ねなく質問してください！
