### ISSUE TITLE
[Open Discussion] "注入する" vs "インジェクトする"

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#300]
現在 angular.jp では `インジェクトする` を `注入する` に校正しています

例) https://angular.jp/tutorial/toh-pt4

![image](https://user-images.githubusercontent.com/1529180/52210532-ad72d680-28ca-11e9-8e29-6190a659179e.png)

しかし、あまり普段使わない日本語であり、かえって分かりづらくなっている可能性もあるため、一度投票をおこなって賛成票が多いものを採用しようと思います。

----

- ❤️ **注入する**
- 🎉 **インジェクトする**
- 😄 **injectする** 

賛成するもののemojiのリアクションをお願いします！コメントでの援護射撃も大歓迎です。

期限: 2/8

**Comment by renamoo** [comment]
Dependency Injectionに対して依存性注入という訳をつけるのであれば、そちらと合わせた方が同じことを話していることがわかりやすいかなーと思うので注入に一票押します！

**Comment by lacolaco** [comment]
みなさんご意見ありがとうございました！ これまで同様、`注入する` を採用することにします。
