### ISSUE TITLE
styleguide 表記ゆれなどなど

### ISSUE THREAD

**Issue by ukyo** [angular/angular-ja#332]
@lacolaco https://angular.jp/guide/styleguide でちょっと気になったところがあったので共有します。

## 表記ゆれ

- プレフィックス、接頭辞
- サフィックス、接尾辞
- フィーチャーモジュール(他のファイルではこれ)、機能モジュール

## markdown記法エラー

- この_フォルダーとファイル構造_の例を参照してください。
- アプリの _ルートモジュール
- _コンポーネント相対_URLは

**Comment by lacolaco** [comment]
ありがとうございます！ たぶん #333 と #331  で解決しそうです。 👍
