### ISSUE TITLE
guide/upgrade.md の翻訳

### ISSUE THREAD

**Issue by amachimura** [angular/angular-ja#345]
### 翻訳するファイル
 - guide/upgrade.md

### 備考
結構長いので、何回かに分けるかもしれません。

cc/ @lacolaco

**Comment by is2ei** [comment]
@lacolaco 
もし止まっていたら続き僕やっても良いでしょうか？ちょうど移行作業に取り組む予定があるためついでにさくっとやっちゃいたいです。

**Comment by lacolaco** [comment]
@is2ei 5月から動いておられないようなので、引き継いでいただけるとありがたいです

**Comment by is2ei** [comment]
@lacolaco 
承知いたしました。250 行ほど（ページ全体の10分の1）翻訳して一旦 PR 立てました。
原文が結構ボリュームあるので、レビューお願いできる段階まで WIP 扱いで立てといても良いでしょうか？ 😅 このプロジェクトの運用的によろしくなかったら閉じますのでお教えください 🙇 
1~2週間あればレビューを依頼できるところまで持っていけると思います（希望的観測
