### ISSUE TITLE
Tracking: Basics

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#35]
- [x] Overview #33 
- [ ] Architecture
- [ ] Display Data
- [ ] User Input
- [ ] Forms
- [ ] Dependency Injection
- [ ] Template Syntax
- [ ] Angular Cheat Sheet
- [ ] Style Guide
- [x] Glossary

**Comment by laco0416** [comment]
https://github.com/angular/angular-ja/projects/1
