### ISSUE TITLE
guide/i18n の翻訳

### ISSUE THREAD

**Issue by silverskyvicto** [angular/angular-ja#351]
### 翻訳するファイル
guide/i18n

### 備考
何回かに分けて翻訳予定

cc/ @lacolaco

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇

**Comment by silverskyvicto** [comment]
何回かに分けてやろうと思いましたが、１回で全部訳せました。
Creating-Library.md がレビュー中なので、それ終わってからでしょうか。

**Comment by lacolaco** [comment]
@silverskyvicto すごい！気にせずPR作ってもらって大丈夫ですよ
