### ISSUE TITLE
guide/glossary の翻訳

### ISSUE THREAD

**Issue by k-neda** [angular/angular-ja#353]
## 翻訳宣言
現在、glossaryが日本国旗マークがついているのに英語のみの表示になっている点が気になっています。
過去の翻訳ファイルがあるようなので、こちらの記述を尊重する形で必要に応じて翻訳を行う形で日本語のファイルを作成させていただいても良いでしょうか？
https://github.com/angular/angular-ja/issues/56

### 翻訳するファイル
guide/glossary

### 備考

cc/ @lacolaco

**Comment by lacolaco** [comment]
@k-neda 大幅な再編があったため追従するのが大変で、一旦原文に戻しておいたものです。ご協力していただけると助かります！
プルリクエストにはこのイシューへのリンクを付与してください 🙇

**Comment by k-neda** [comment]
@lacolaco　書き方に棘があるように感じてしまったのならごめんなさい。お早いメンションいただきありがとうございます。かしこまりました。

**Comment by lacolaco** [comment]
長い間アクションがないためcloseさせていただきます。再開する際はあらためてチェックアウトをお願いします。
