### ISSUE TITLE
[PR募集] guide/singleton-services の翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#368]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

https://github.com/angular/angular-ja/pull/367 で原文を残した部分の追加翻訳を募集します

https://github.com/angular/angular-ja/pull/367/commits/4d54bbd275be31d33c3f959cbc919a94729e3913

- singleton-services.md

**Comment by hoshima** [comment]
翻訳に挑戦してみたいです！

**Comment by lacolaco** [comment]
@hoshima ありがとうございます！ぜひお願いします！
変更のプルリクエストを出していただいて、このイシューへのリンクを付与してください 🙇
