### ISSUE TITLE
[PR募集] guide/workspace-config の翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#369]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

https://github.com/angular/angular-ja/pull/367 で残した未翻訳部分の追加翻訳を募集します
https://github.com/angular/angular-ja/pull/367/commits/462702baf1bf1bd8a1e8782df74a604e384cf0a2

- workspace-config.md

**Comment by k-ta-yamada** [comment]
やります 🙌

**Comment by lacolaco** [comment]
たくさんコントリビューションありがとうございます！よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇

**Comment by k-ta-yamada** [comment]
こちらこそ、コントリビューションしつつ学習も進むのでありがたいです 🙇
