### ISSUE TITLE
[PR募集] start/routing の翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#374]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

- start/routing.md https://angular.jp/start/routing

**Comment by ver-1000000** [comment]
@lacolaco やりますッ！！！！✋

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
