### ISSUE TITLE
[PR募集] start/data の翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#375]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

- start/data.md https://angular.jp/start/data

**Comment by k-ta-yamada** [comment]
🙌 数日かかるかもしれませんが、よろしければ。

**Comment by lacolaco** [comment]
ありがとうございます！よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
