### ISSUE TITLE
[PR募集] cli/index.md の翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#378]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

- cli/index.md https://angular.jp/cli

**Comment by k-ta-yamada** [comment]
やってみたいです（機械翻訳をベースに、になりそうですが）。

実は以前翻訳に挑戦しようと思ったのですが、
`Command Overview`のについてはcliのソースから生成されていたようで、
どうやって翻訳を実施していいか検討がつきません。。。😅

**Comment by lacolaco** [comment]
@k-ta-yamada ぜひよろしくお願いします！ 🙌
機械翻訳ベースでまったく問題ありません。
プルリクエストにはこのイシューへのリンクを付与してください 🙇

ソースから生成されているドキュメンテーションは翻訳できないですね...
