### ISSUE TITLE
[PR募集] cli/usage-analytics-gathering の翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#379]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

- cli/usage-analytics-gathering.md https://angular.jp/cli/usage-analytics-gathering

**Comment by k-ta-yamada** [comment]
✋ チャレンジしてみます。

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
