### ISSUE TITLE
[PR募集] guide/file-structure の追加翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#381]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

- guide/file-structure: https://angular.jp/guide/file-structure

### 備考

8.0.0アップデート時に残した原文の追加翻訳をおねがいします！

**Comment by k-ta-yamada** [comment]
やってみます 🙌

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
