### ISSUE TITLE
guide/schematicsの翻訳

### ISSUE THREAD

**Issue by mana-vv** [angular/angular-ja#419]
### 翻訳するファイル

guide/schematics

### 備考
特にありません。

cc/ @lacolaco

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇

**Comment by lacolaco** [comment]
長い間アクションがないためcloseさせていただきます。再開する際はあらためてチェックアウトをお願いします。
