### ISSUE TITLE
submodule で管理している本家リポジトリの package.json の差異

### ISSUE THREAD

**Issue by silverskyvicto** [angular/angular-ja#421]
Submodule として追従している本家リポジトリの中で、複数ある package.json の中に記載されている yarn のエンジンのバージョンが異なる。

yarn のエンジンのバージョン
- origin 直下の package.json: ">=1.12.1 <=1.16.0"
- aio ディレクトリ直下の package.json: ">=1.12.1 <=1.14.0"
- tools/example/shared ディレクトリの下の package.json: ">=1.10.1 <1.14.0"

これが影響しているのか、yarn 1.16.0 で ./build.sh を実行した時に以下のエラーが表示される。
```
yarn run v1.16.0
error angular.io@0.0.0: The engine "yarn" is incompatible with this module. Expected version ">=1.12.1 <=1.14.0". Got "1.16.0"
error Commands cannot run with an incompatible environment.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by lacolaco** [comment]
#425 で解決するかもしれません。

**Comment by silverskyvicto** [comment]
@lacolaco 
そうでしたか。
ではこれはクローズします。
また何かあればオープンするかも。
