### ISSUE TITLE
[PR募集] guide/hierarchical-dependency-injection の再翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#427]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

guide/hierarchical-dependency-injection

### 備考

#426 にて旧バージョンから大きく内容が変わったため、古いバージョンを `.md.old` ファイルに退避し、日本語化を解除しています。
再翻訳の際には古い翻訳から再利用できる部分を活用してもらえればと思います

**Comment by ukyo** [comment]
@lacolaco やります 🙋‍♂

**Comment by lacolaco** [comment]
@ukyo 遅くなりました！ぜひよろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇

**Comment by ukyo** [comment]
@lacolaco https://github.com/angular/angular/pull/32501 翻訳中にみつけた原文の間違いを修正してもらったので、都合の良いタイミングで追いつきをお願いします 🙇
