### ISSUE TITLE
guide/angular-compiler-options.md の翻訳

### ISSUE THREAD

**Issue by silverskyvicto** [angular/angular-ja#429]
### 翻訳するファイル
guide/angular-compiler-options.md

### 備考

cc/ @lacolaco

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇

**Comment by lacolaco** [comment]
aot-compilerから移動されたセクションが主で、8.2.3にバージョンアップするときにaot-compilerから省かれた部分を `.md.old` として退避してます。再利用できるかとおもいます
