### ISSUE TITLE
api-page-class.md の翻訳

### ISSUE THREAD

**Issue by is2ei** [angular/angular-ja#437]
### 翻訳するファイル
api-page-class.md

### 備考
N/A

cc/ @lacolaco

**Comment by lacolaco** [comment]
宣言ありがとうございます！
しかしおそらくですがこのファイルは実際にはドキュメンテーションには使われていないファイルだと思いますので、翻訳は不要です。別のドキュメントを翻訳していただけるとありがたいです。
