### ISSUE TITLE
guide/cli-builder の翻訳

### ISSUE THREAD

**Issue by pachirel** [angular/angular-ja#472]
### 翻訳するファイル

aio-ja/content/guide/cli-builder.md

### 備考

cc/ @lacolaco

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇

**Comment by lacolaco** [comment]
長い間アクションがないためcloseさせていただきます。再開する際はあらためてチェックアウトをお願いします。
