### ISSUE TITLE
aot-compiler.md の再翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#483]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

aot-compiler.md (一部）

**Comment by big-stream** [comment]
@lacolaco なるはやでやります

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
