### ISSUE TITLE
architecture-next-steps.md の翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#484]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

architecture-next-steps.md （一部）

**Comment by rch850** [comment]
軽そうなので着手します 🤚 

ほかも並行して翻訳してますが、とりあえず issue 減らしとして。

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
