### ISSUE TITLE
guide/architecture.md の翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#485]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

guide/architecture.md (一部）

**Comment by aqlwah** [comment]
やりたいです:raised_hands:

**Comment by aqlwah** [comment]
@lacolaco 
やりたいです:raised_hands:

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
