### ISSUE TITLE
guide/language-service.md の翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#488]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

guide/language-service.md

**Comment by Quramy** [comment]
Language Service、好きなのでやりたいです。直近すぐは厳しいですが、2月中くらいにはできます。

**Comment by lacolaco** [comment]
ぜひよろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
