### ISSUE TITLE
[PR募集] guide/service-worker-devops.md の翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#489]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

guide/service-worker-devops.md (一部）

**Comment by sam8helloworld** [comment]
@lacolaco
残りの一部翻訳しますー✋

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇

**Comment by sam8helloworld** [comment]
了解ですー！やっていきます。
