### ISSUE TITLE
http.md の翻訳

### ISSUE THREAD

**Issue by studioTeaTwo** [angular/angular-ja#49]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

- http.md

**Comment by lacolaco** [comment]
よろしくお願いします！プルリクエストにはこのIssueへのリンクを付与してください。
