### ISSUE TITLE
guide/workspace-config.md の翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#490]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

guide/workspace-config.md （一部）

**Comment by silverskyvicto** [comment]
@lacolaco 
頑張ってみます

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
