### ISSUE TITLE
guide/i18n.md の翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#492]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

guide/i18n.md (一部）

**Comment by silverskyvicto** [comment]
@lacolaco 
やってみます

**Comment by lacolaco** [comment]
@silverskyvicto ありがとうございます！しかし今他にも2つアサインされているので、どちらかが終わってからアサインさせていただきます。それまでに誰かが宣言されたらそちらの方にお願いします。

**Comment by silverskyvicto** [comment]
@lacolaco 
これどうでしょうか。
一応翻訳したものがあるので、プルリク送ることはできますが。

以下はすでに終わったと思っているので。
- #259
- #387
- #490

**Comment by lacolaco** [comment]
@silverskyvicto はい！ぜひよろしくおねがいします！
