### ISSUE TITLE
guide/lazy-loading-ngmodules.md の翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#493]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

guide/lazy-loading-ngmodules.md （一部）

**Comment by ukyo** [comment]
@lacolaco やります!

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
