### ISSUE TITLE
guide/typescript-configuration.md の翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#494]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

guide/typescript-configuration.md (一部）

**Comment by y4m4to** [comment]
@lacolaco 初めてですが、こちらの翻訳をやりたいです！

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
