### ISSUE TITLE
tutorial/toh-pt3.mdの翻訳

### ISSUE THREAD

**Issue by massa142** [angular/angular-ja#50]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

*  tutorial/toh-pt3.md

### 備考

去年進めてた #32 をやり直そうと思います。

**Comment by lacolaco** [comment]
よろしくお願いします！
プルリクエストにはこのイシューへのリンクを付与してください

**Comment by lacolaco** [comment]
こちら作業完了してましたらcloseお願いします
