### ISSUE TITLE
guide/zone の翻訳

### ISSUE THREAD

**Issue by aqlwah** [angular/angular-ja#504]
### 翻訳するファイル

guide/zone.md

### 備考
NgZoneのドキュメントが追加されたようです。
個人的に気になる機能でもありますので、ぜひ翻訳したいです:bow:
https://angular.io/guide/zone

cc/ @lacolaco

**Comment by lacolaco** [comment]
まだ翻訳元の本家ファイルを更新できていないので、それが終わったらぜひお願いします！来週中にはできると思います

**Comment by aqlwah** [comment]
すみません、うっかりしてました:bow::sweat_drops:
更新ができたら着手します。

**Comment by lacolaco** [comment]
https://angular.jp/guide/zone zoneのドキュメントを準備しました！ 翻訳可能になったのでぜひよろしくおねがいします！

**Comment by aqlwah** [comment]
ありがとうございます🙏
着手します！
