### ISSUE TITLE
guide/template-syntax の翻訳

### ISSUE THREAD

**Issue by rch850** [angular/angular-ja#505]
### 翻訳するファイル

guide/template-syntax.md

### 備考

量が多いので、少しずつ進めていきたいと思います。
[こちらの PR コメント](https://github.com/angular/angular-ja/pull/361#issuecomment-517928799)で触れられている template-syntax.md.backup も参考にしていきます。

cc/ @lacolaco

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
