### ISSUE TITLE
tutorial/toh-pt1.mdの翻訳

### ISSUE THREAD

**Issue by imamoto** [angular/angular-ja#51]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

* tutorial/toh-pt1.md

### 備考

まずは1ページだけ担当させてください。

**Comment by lacolaco** [comment]
よろしくお願いします！
プルリクエストにはこのイシューへのリンクを付与してください

**Comment by lacolaco** [comment]
こちら作業完了してましたらcloseお願いします
