### ISSUE TITLE
キャッシュのない来訪で、ページが`RESOURCE NOT FOUND`となる

### ISSUE THREAD

**Issue by ver-1000000** [angular/angular-ja#519]
# 問題概要
去年ぐらいから「存在してるはずのドキュメントのページで、RESOURCE NOT FOUNDになることがあるな……」と思っていたのですが、  
**初めての来訪**や**キャッシュを削除した更新**で、**RESOURCE NOT FOUNDになったりサイドバーが消えたり**します。

# 再現環境・手法
Archlinux / GoogleChrome[80.0.3987.132（Official Build）]
- プライベートブラウザでページを開く
- 「Shift + Ctrl + R」によるページリロード
![output](https://user-images.githubusercontent.com/6778957/76521240-c1164680-64a7-11ea-97c6-31ebeddae898.gif)

サイドバーが表示されない現象は再現できなかったのですが、  
Twitterで共有された、初めて見るドキュメントのページのリンクをクリックした時になったと思います。

**Comment by lacolaco** [comment]
報告ありがとうございました！Netlifyのリダイレクト設定で修正できました！
