### ISSUE TITLE
tutorial/toh-pt0.mdの翻訳

### ISSUE THREAD

**Issue by Allajah** [angular/angular-ja#52]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

- tutorial/toh-pt0.md

**Comment by lacolaco** [comment]
よろしくお願いします！
プルリクエストにはこのイシューへのリンクを付与してください
