### ISSUE TITLE
Re: Angular document for Japanese

### ISSUE THREAD

**Issue by javakiller0606** [angular/angular-ja#536]
I am writing to ask about Angular document for Japanese.

It seems that the imported part of the attached image is missing.

Isn't "import {Component, OnInit} from '@ angular / core';" correct?

Could you please confirm it?
<img width="900" alt="2020-05-13" src="https://user-images.githubusercontent.com/52107468/81875087-72c21880-95ba-11ea-8d27-56ec043c823b.png">

**Comment by lacolaco** [comment]
You can check the original version at https://angular.io/start/start-data#display-the-cart-items . This localization project prioritizes synchronization with the original English version. 
If you feel the documentation is wrong or not friendly, please submit an issue to  [angular/angular](https://github.com/angular/angular) repository.
Thanks.
