### ISSUE TITLE
router-tutorial.mdの翻訳

### ISSUE THREAD

**Issue by t-cool** [angular/angular-ja#551]
### 翻訳するファイル

router-tutorial.md

https://github.com/angular/angular-ja/edit/master/aio-ja/content/guide/router-tutorial.md

### 備考

cc/ @lacolaco

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇

**Comment by t-cool** [comment]
了解しました！時間を作って翻訳進めます！
