### ISSUE TITLE
guide/quickstart.mdの翻訳

### ISSUE THREAD

**Issue by Pittan** [angular/angular-ja#60]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル
guide/quickstart.md

**Comment by lacolaco** [comment]
よろしくお願いします！
プルリクエストにはこのイシューへのリンクを付与してください
