### ISSUE TITLE
guide/router.md の翻訳

### ISSUE THREAD

**Issue by nana4gonta** [angular/angular-ja#618]
### 翻訳するファイル

guide/router.md

### 備考

再翻訳でまだ誰もチェックが入ってなかったようなのでお手伝いさせてください

cc/ @lacolaco

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇

**Comment by lacolaco** [comment]
長い間アクションがないためcloseさせていただきます。再開する際はあらためてチェックアウトをお願いします。
