### ISSUE TITLE
[配送料を取得するために CartService を設定します。] 部分のサンプルコードの修正はどうすればいいでしょうか？

### ISSUE THREAD

**Issue by ikepon** [angular/angular-ja#623]
日本語ページ[配送料を取得するために CartService を設定します。](https://github.com/angular/angular-ja/blob/master/aio-ja/content/start/start-data.md#%E9%85%8D%E9%80%81%E6%96%99%E3%82%92%E5%8F%96%E5%BE%97%E3%81%99%E3%82%8B%E3%81%9F%E3%82%81%E3%81%AB-cartservice-%E3%82%92%E8%A8%AD%E5%AE%9A%E3%81%97%E3%81%BE%E3%81%99) 部分のサンプルコードが[英語ページ](https://angular.io/start/start-data#configure-cartservice-to-get-shipping-prices)と違っていて動かなかったので、PRを出そうと思ったんですが修正の仕方が分かりませんでしたので、issue で挙げさせてもらいました。

```diff
export class CartService {
  items = [];

  constructor(
    private http: HttpClient
  ) {}

  addToCart(product) {
    this.items.push(product);
  }

  getItems() {
    return this.items;
  }

  clearCart() {
    this.items = [];
    return this.items;
  }

  getShippingPrices() {
-    return this.http.get('/assets/shipping.json');
+    return this.http.get<{type: string, price: number}[]>('/assets/shipping.json');
  }
}
```

**Comment by lacolaco** [comment]
修正します！報告ありがとうございます！
