### ISSUE TITLE
翻訳作業時に使用する node version の記載

### ISSUE THREAD

**Issue by shioyang** [angular/angular-ja#635]
ローカルで翻訳作業をしようとしたときに、node version がぱっとわからなかったので、どこかに記載があると迷わないと思います。
現状 `v12.*` でしょうか。

e.g.
- `"engines"` in package.json
- [CONTRIBUTING.md](https://github.com/angular/angular-ja/blob/master/CONTRIBUTING.md)
- `.nvmrc`

**Comment by lacolaco** [comment]
`.node-version` ファイルを追加しました！  7d54e77480ba3e5bf465f07202244415e8c3fff6
