### ISSUE TITLE
dependency-injection.md の翻訳

### ISSUE THREAD

**Issue by shioyang** [angular/angular-ja#636]
### 翻訳するファイル

[dependency-injection.md](https://github.com/angular/angular-ja/blob/master/aio-ja/content/guide/dependency-injection.md)
（更新があった部分の翻訳）

### 備考

cc/ @lacolaco

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
