### ISSUE TITLE
[PR募集] i18n系ガイドの翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#688]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

https://angular.jp/guide/i18n-overview

- [x] i18n-overview.md
- [x] i18n-common-add-package.md
- [ ] i18n-common-deploy.md
- [x] i18n-common-format-data-locale.md
- [x] i18n-common-locale-id.md
- [x] i18n-common-merge.md
- [x] i18n-common-overview.md
- [x] i18n-common-prepare.md
- [x] i18n-common-translation-files.md
- [ ] i18n-example.md
- [x] i18n-optional-import-global-variants.md
- [x] i18n-optional-manage-marked-text.md
- [x] i18n-optional-manual-runtime-locale.md
- [x] i18n-optional-overview.md

### 備考

- 1ページずつでも、いくつかのページをまとめて1つのPRにしても、どちらでも大丈夫です

**Comment by nishitaku** [comment]
やります！

**Comment by lacolaco** [comment]
> やります！

ありがとうございます！プルリクエストにはこのイシューへのリンクを付与してください 🙇

**Comment by IRod22** [comment]
来週末から他のファイルを翻訳できるはずです。

**Comment by nishitaku** [comment]
@IRod22 
他のファイルの翻訳は進めていますか？

**Comment by IRod22** [comment]
@nishitaku
これらのファイルに手をつけなかったことをお詫びします。このスレッドの参加者の確認を待っていたので、他の人の邪魔にならないようにします。

**Comment by IRod22** [comment]
@lacolaco @nishitaku ドラフトで指名された： #838

**Comment by IRod22** [comment]
@lacolaco @nishitaku 約束したほどの翻訳ができず、とても残念です。 🤦‍♂️ 大学の授業がとても忙しく、ファイナルの期末テストに集中する必要がありました。私はプルリクエストをレビューのために準備しました。
