### ISSUE TITLE
[PR募集] update-to-latest-version.md の翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#690]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

- [x] guide/update-to-latest-version.md https://angular.jp/guide/update-to-latest-version

**Comment by komura-c** [comment]
こちらやりたいです！

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
