### ISSUE TITLE
[PR募集] guide/angular-package-format.md の翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#692]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

- [ ] guide/angular-package-format.md https://angular.jp/guide/angular-package-format

### 備考

けっこう長くて面倒です

**Comment by IRod22** [comment]
@lacolaco 私はこれの世話をします ！ #799 の出来次第で、一日で完成できるはずです。 これをいつ翻訳できるようになるか見てみましょう。

**Comment by IRod22** [comment]
@lacolaco、このファイルを翻訳する準備がすべて整っています。 木曜日 (私の時間) までに翻訳できますが、翻訳の許可を必ず取っておいてください。

**Comment by lacolaco** [comment]
@IRod22 よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください

**Comment by IRod22** [comment]
@lacolaco 今夜中にファイルを翻訳できると思います。いつプル リクエストを開くことができるかを確認します。

**Comment by IRod22** [comment]
@lacolaco 今夜中にファイルを翻訳できると思います。いつプル リクエストを開くことができるかを確認します。

**Comment by IRod22** [comment]
@lacolaco、この問題を閉じるのを忘れていませんか？
