### ISSUE TITLE
guide/cheatsheet.md の翻訳

### ISSUE THREAD

**Issue by adwd** [angular/angular-ja#71]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

guide/cheatsheet.md

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
