### ISSUE TITLE
guide/interpolation の翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#746]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

- guide/interpolation https://angular.jp/guide/interpolation

### 備考

- 短いのではじめてのコントリビューションにおすすめです。

**Comment by 2YY** [comment]
@lacolaco 
こちら、よければ対応させていただきます！

**Comment by lacolaco** [comment]
@2YY よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
