### ISSUE TITLE
[PR募集] guide/binding-overview の翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#747]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

- https://angular.jp/guide/binding-overview

### 備考

- 比較的短いのではじめてのコントリビュートにおすすめです。

**Comment by ver-1000000** [comment]
やります！ 来週の日曜日くらいまでにPR出せればと思います。

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
