### ISSUE TITLE
[PR募集] guide/attribute-binding の翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#748]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

- https://angular.jp/guide/attribute-binding

### 備考

- 短いのではじめてのコントリビュートにおすすめです。

**Comment by sugar-cat7** [comment]
@lacolaco 
こんにちは！
こちら翻訳してもよろしいでしょうか？👀

**Comment by lacolaco** [comment]
@sugar-cat7 
はい！よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
