### ISSUE TITLE
[PR募集] guide/class-binding の翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#749]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

- https://angular.jp/guide/class-binding

### 備考

- 短いのではじめてのコントリビュートにおすすめです。

**Comment by IRod22** [comment]
こんにちは、@lacolaco です。 このファイルを翻訳してもよろしいですか？ 私は日本人でも日本出身でもないことを知っています、そして私はまだ日本語を学んでいます：
- 私は基本的な日本語の文法を知っています、
- ひらがなとカタカナは全部知ってる、
- 基本漢字の部首と基本漢字の意味を知っている、
- カタカナのほとんどの単語の意味がわかります。

しかし、基本的なドキュメントを翻訳することで、私たち双方に利益をもたらすことができると思います。私は現実世界の日本語を勉強し、交流することができ、翻訳するドキュメントが 1 つ少なくなります。そうは言っても、私が文書を日本語に翻訳することについてあなたが懐疑的であることは認めます。
- タイムゾーンが異なると、状況に応じてワークフローが速くなったり遅くなったりする可能性があります。
- マークダウン リンクは Google 翻訳を混乱させる可能性があり (文のどの部分を折り返すかによって異なりますが、**太字** や *イタリック体* のコンテンツには適しています)、1 つの単語が表示されているのか、それとも単語が表示されているのかを判断するのは少し困難です。 二つの単語。
- リスト、テーブル、Angular 固有の構文などのより複雑な Markdown 構文は、英語と日本語の両方で文の構造を変更する可能性があるため、ワークフローを遅くするより多くの問題につながる可能性があります。
- 最後に、私は自分が*している*自由な時間をボランティア活動しているので、これを 1 日で終わらせるのに十分な時間がないかもしれません。

これらの事実を念頭に置いて、あなたが私の申し出を断ってもかまいません。ここでコミュニティに貢献してから数日が経過したことを理解しています。あなたが受け入れるなら、確立されたコミットスタイルがあるかどうかを知る必要があります。 セマンティック コミットとは異なるスタイルを使用する場合があることは知っているので、コミュニティのガイドラインに従っていることを確認したいだけです。いずれにせよ、コミュニティに貢献できることを嬉しく思います。

**Comment by lacolaco** [comment]
@IRod22 もちろん歓迎します！ No problem! 緊急のプロジェクトではないためタイムゾーンには何の問題もありません。
このレポジトリにおける翻訳のガイドラインは https://github.com/angular/angular-ja/blob/main/CONTRIBUTING.md に書いていますが、このガイドラインに理解できない部分があれば、 https://github.com/angular/angular-ja/discussions/categories/q-a でおしえてください。

**Comment by IRod22** [comment]
とった！ 今夜何ができるか見て、ドラフト PR を開いて、進行状況を追跡できるようにします。ありがとうございました！

**Comment by IRod22** [comment]
@lacolaco、Q&A で質問しようと思ったのですが、ディスカッションを開くボタンが表示されませんでした。:thinking: リポジトリのクローンを作成しようとしましたが、アクセス許可に関する致命的なエラーが発生しました:

```bash
$ git clone git@github.com:angular/angular-ja.git
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

$ 
```

これについて問題を開く必要がありますか? ところで、私はWindowsマシンを使用しています。

**Comment by IRod22** [comment]
@lacolaco、私は問題が何であるかを知っていると思います。私の記憶が正しければ、GitHub はセキュリティを強化しており、そのため、最初にフォークしないとリポジトリを複製できないと思います。現在、このリポジトリのフォークでサブモジュールを同期する方法の解決策を探しているので、試してみることができます。解決策が見つかり次第ご報告しますが、CONTRIBUTING.md ファイルを更新する必要があると言えます。

**Comment by IRod22** [comment]
これには、予想よりも時間がかかる場合があります。@lacolaco、あなたがこれを見るまでに答えが見つからない場合は、助けが必要かもしれません。[StackOverflow](https://stackoverflow.com/questions/68119419/syncing-forked-repository-with-forked-submodules-and-original-repository-with-or) で 1 つの答えを見つけましたが、少し難しいようです。

**Comment by IRod22** [comment]
解決策を見つけました！問題を解決するために私が取った手順は次のとおりです:
1. GitHub でリポジトリをフォークします。
2. フォークを自分のコンピューターに複製します。
3. VS Code を使用してフォークを同期します: `Source Control` -> 更新ボタンの横にある 3 つのドットをクリックします -> `Pull, Push` -> `Sync`

通常のワークフローは、ステップ 3 の後に機能するはずです。:relieved: コマンドラインでステップ3を実行する方法をまだ見つけていません。
