### ISSUE TITLE
[PR募集] guide/property-binding の翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#751]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

- https://angular.jp/guide/property-binding

### 備考

- 短いのではじめてのコントリビュートにおすすめです。

**Comment by plageoj** [comment]
初めてですがやってみようと思います！
