### ISSUE TITLE
[PR募集] guide/pipes-transform-data の翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#754]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

https://angular.jp/guide/pipes-transform-data

### 備考

- 短いのではじめてのコントリビュートにおすすめです。

**Comment by darkss-xyzzy** [comment]
@lacolaco さん

こちらの方、私の方で着手したいと思いますが、
宜しいでしょうか？

**Comment by lacolaco** [comment]
ぜひ、よろしくお願いします！ 🙌

**Comment by darkss-xyzzy** [comment]
@lacolacoさん

お待たせしました。
和訳の方ができましたので、pull requestを作成しました。
レビューをお願いします。
