### ISSUE TITLE
[PR募集] guide/change-detection-slow-computations の翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#760]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

https://angular.jp/guide/change-detection-slow-computations

### 備考

- 短いのではじめてのコントリビュートにおすすめです。

**Comment by kasaharu** [comment]
@lacolaco 翻訳します！

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
