### ISSUE TITLE
[PR募集] guide/image-directive の翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#763]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

https://angular.jp/guide/image-directive

**Comment by 2YY** [comment]
@lacolaco 
こちら、対応します！ (image-directive 繋がりで・・)

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
