### ISSUE TITLE
[PR募集] guide/lightweight-injection-tokens の翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#764]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

https://angular.jp/guide/lightweight-injection-tokens

**Comment by 2YY** [comment]
@lacolaco 
こちら、良ければ対応いたします！

**Comment by lacolaco** [comment]
@2YY ありがとうございます！よろしくおねがいします！
