### ISSUE TITLE
[PR募集] guide/deployment の翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#765]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

https://angular.jp/guide/deployment

**Comment by darkss-xyzzy** [comment]
@lacolaco さん

こちらのドキュメント、私の方で翻訳して良いでしょうか？
長めなのでお時間いただくとは思いますが。

**Comment by lacolaco** [comment]
@darkss-xyzzy ぜひよろしくお願いします！

**Comment by lacolaco** [comment]
長い間アクションがないためcloseさせていただきます。
