### ISSUE TITLE
[PR募集] guide/devtools の翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#766]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

https://angular.jp/guide/devtools

**Comment by 2YY** [comment]
@lacolaco 
こちら、対応可能です！

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
