### ISSUE TITLE
[PR募集] guide/image-directive-setup の翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#767]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

https://angular.jp/guide/image-directive-setup

**Comment by 2YY** [comment]
@lacolaco 
こちら、よければ対応させて頂きます！

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
