### ISSUE TITLE
[PR募集] guide/standalone-components の翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#768]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

https://angular.jp/guide/standalone-components

**Comment by komura-c** [comment]
こちら、対応させていただきたいです！

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
