### ISSUE TITLE
[PR募集] guide/cli-builder の翻訳

### ISSUE THREAD

**Issue by lacolaco** [angular/angular-ja#769]
## 翻訳者募集

未翻訳ドキュメントを翻訳者を募集します。
コントリビューションできる方はコメントで挙手してください！ 

### 翻訳してほしいファイル (URL)

https://angular.jp/guide/cli-builder

**Comment by IRod22** [comment]
@lacolaco,

angular/angular#48129 がマージされるまで待つことをお勧めします。これには、他の問題やプル リクエストのバックログがあるため、しばらく時間がかかる場合があります。元のファイルに小さいながらも目立つタイプミスが検出されたため、マージが行われる可能性があります。 タイプミスの*ない*ファイルが、タイプミス*のある*翻訳済みファイルとともにこのリポジトリにマージされた場合に競合します。

タイムゾーンが異なるため、このことをあなたとコミュニティの他のメンバーに知らせたいと思いました。

**Comment by IRod22** [comment]
@lacolaco、プル リクエストは次のパッチ リリースでマージする必要があります。 マージが完了すると、`angular:main` と同期できるはずです。

追記 解決策を見つけたと思うので、#780 を確認 (および場合によっては終了) することをお勧めします。

**Comment by IRod22** [comment]
プルリクエストは気にしないでください。 タイプミスを修正するコミットのために閉じられました。 ただし、変更がメイン ブランチ (おそらく次のパッチ リリース) に到達するまでにはしばらく時間がかかると確信しています。

**Comment by lacolaco** [comment]
@IRod22 Thank you for your information!
