### ISSUE TITLE
guide/displaying-data.md の翻訳

### ISSUE THREAD

**Issue by imamoto** [angular/angular-ja#78]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

guide/displaying-data.md

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇

**Comment by lacolaco** [comment]
@imamoto #133 で新しく挙手されていますが、こちら進行中でしょうか？

**Comment by mitsuhisaT** [comment]
ごめんなさい、見落としました。
#133 取り下げます。

**Comment by lacolaco** [comment]
長い間アクションがないためcloseさせていただきます。再開する際はあらためてチェックアウトをお願いします。
