### ISSUE TITLE
[おすすめ] スペル チェックに VS Code 拡張機能を使用する

### ISSUE THREAD

**Issue by IRod22** [angular/angular-ja#797]
最近、作業中の `.md` にスペルと文法のエラーがあることを知らせてくれる、クールなエディタ拡張機能を見つけました。この拡張機能は[「Spell Right」](https://marketplace.visualstudio.com/items?itemName=ban.spellright)と呼ばれ、スペル ミスのない RFC やドキュメントを作成するために使用しています。日本の Angular コミュニティにこのことを伝えたいと思った理由は、この拡張機能が多言語サポートを備えているためです。この拡張機能は、`CONTRIBUTING.md` で新規参入者に推奨する必要があるためです。 時間があるときは自分でそれを行うことができ、コミュニティは私がそうすることを気にしません.

私の推奨事項に関するコミュニティからのフィードバックをお待ちしております。ドキュメントの翻訳ワークフローが改善されることを願っています!

**更新**: これは Discord チャットに投稿すべき提案であることに気付きました。 ただし、Discord全体についていくつか悪いことを聞いたので、参加することに不安を感じています。おそらく言語の壁が原因で、サーバーで親指のように目立ちたくありません。 これらの理由から、私はこの問題を開いたままにします。 ご理解いただきありがとうございます。

**Comment by IRod22** [comment]
@lacolaco、拡張機能についてどう思いますか?

**Comment by lacolaco** [comment]
@IRod22 このレポジトリでは https://github.com/prh/prh と https://github.com/textlint/textlint を使って日本語の校正をしています。これらのツールのルールを利用できる拡張機能ならよいですが、そうでないなら複数のルールが混在することになるので推奨できないと考えています。

**Comment by IRod22** [comment]
オーケー！この問題をクローズします。
