### ISSUE TITLE
guide/ngmodule.md の翻訳

### ISSUE THREAD

**Issue by Allajah** [angular/angular-ja#80]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

- guide/ngmodule.md

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇

**Comment by lacolaco** [comment]
#115 で同期される最新のoriginで、ngmodule.mdがなくなっています。いくつかのドキュメントに分割されたようですので、すみませんがcloseさせていただきます。
流用できる部分もあるかもしれませんので、中断して翻訳文を退避したのち、新しいドキュメントの翻訳に活用していただけると幸いです。
