### ISSUE TITLE
tutorial/toh-pt6.mdの修正

### ISSUE THREAD

**Issue by chloe463** [angular/angular-ja#81]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [ ] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [x] その他
```

### 翻訳するファイル
tutorial/toh-pt6.md

### 備考

* 一部マークダウンが反映されていない部分の修正。
* 一部ソース・ファイル内のコメントが修正されていない部分の修正。

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
