### ISSUE TITLE
guide/aot-compiler.md の翻訳

### ISSUE THREAD

**Issue by ntaoo** [angular/angular-ja#82]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

guide/aot-compiler.md

### 備考

もしもaot-compilerの原文がこれから大幅にアップデートされるといった雰囲気ならば別のファイルにするかもしれません。

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇

ファイルを変更する場合はこのissueをcloseして、新しいissueを作成してください

**Comment by lacolaco** [comment]
長い間アクションがないためcloseさせていただきます。再開する際はあらためてチェックアウトをお願いします。
