### ISSUE TITLE
guide/attribute-directives.mdの翻訳

### ISSUE THREAD

**Issue by TomohiroAkutsu** [angular/angular-ja#87]
cc/ @lacolaco,
### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル
guide/attribute-directives.md

### 備考

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇

**Comment by lacolaco** [comment]
完了したためcloseします。
