### ISSUE TITLE
guide/testing.mdの翻訳

### ISSUE THREAD

**Issue by gurezo** [angular/angular-ja#88]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル
guide/testing.md

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇

**Comment by lacolaco** [comment]
長い間アクションがないためcloseさせていただきます。再開する際はあらためてチェックアウトをお願いします。
