### ISSUE TITLE
guide/service-worker-getting-started.mdの翻訳

### ISSUE THREAD

**Issue by studioTeaTwo** [angular/angular-ja#94]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

service-worker-getting-started.md

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇

**Comment by studioTeaTwo** [comment]
#97 にまとめてるのでクローズします。
