### ISSUE TITLE
guide/universal.mdの翻訳

### ISSUE THREAD

**Issue by MasanobuAkiba** [angular/angular-ja#96]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

universal.md

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇

**Comment by lacolaco** [comment]
こちら完了ということでcloseします
