### ISSUE TITLE
guide/service-worker-*.mdの翻訳

### ISSUE THREAD

**Issue by studioTeaTwo** [angular/angular-ja#97]
cc/ @lacolaco,

### イシューの目的 (`x`マークをつけてください)
```
- [x] 翻訳の宣言
- [ ] プロジェクトへの要望・意見
- [ ] その他
```

### 翻訳するファイル

guide/service-worker-getting-started.md
guide/service-worker-communications.md
guide/service-worker-devops.md
guide/service-worker-config.md

### 備考

PRは1個ずつ行きます

**Comment by lacolaco** [comment]
よろしくお願いします！ 🙌
プルリクエストにはこのイシューへのリンクを付与してください 🙇
